name = "monty-db"
type = "javascript"
account_id = "a574887f781a5eb9ca21e1fab8627bd0"
workers_dev = true
compatibility_date = "2021-12-29"
webpack_config = "webpack.config.js"

kv_namespaces = [
    { binding = "MONTY_DB", id = "c40390b0155d46baaf72b704f760de03", preview_id = '938af974f9684bbaab63ce6c5c7530d9' },
]


[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"


# [secrets]
# MONTY_DB_TOKEN


[miniflare]
kv_persist = "redis://localhost:6379"
port = 8555