name = "monty-db"
type = "javascript"
account_id = "a574887f781a5eb9ca21e1fab8627bd0"
workers_dev = true
compatibility_date = "2021-12-29"
webpack_config = "webpack.config.js"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.dev]
kv_namespaces = [
    { binding = "MONTY_DB", id = "dea7faea56d14a47bbb18004d7410f73", preview_id = 'c65433e4705948ee856cbf181e9765b8' },
]

[env.prod]
kv_namespaces = [
    { binding = "MONTY_DB", id = "c40390b0155d46baaf72b704f760de03" },
]

# [secrets]
# MONTY_DB_TOKEN
